### ISSUE TITLE
Magento 2.2.0: .gitignore file should ignore /generated/ directory

### ISSUE THREAD

**Issue by hostep** [magento/magento-cloud#38]
### Preconditions
1. Git version 2.14.2 (seems the be the only relevant software package here)

### Steps to reproduce
1. Having a Magento 2.1.9 Cloud project
2. Upgrade it to Magento 2.2.0 using http://devdocs.magento.com/guides/v2.2/cloud/project/project-upgrade.html
3. Run: `git add -A`
3. Run: `bin/magento --version`
4. Run: `git status`

### Expected result
1. Not seeing files listed from the '/generated/' directory

### Actual result
1. Seeing a whole bunch of files from the '/generated/' directory

### Discussion
I think these two lines need to be added to the `.gitignore` file:
```
/generated/*
!/generated/.htaccess
```

**Comment by hostep** [comment]
Also (if I need to create a new ticket, please let me know): the `.gitignore` file isn't being updated when upgrading from 2.1.9 to 2.2.0 using composer. Either this should happen automatically, or it should be mentioned in the documentation that you'll need to compare the content of your `.gitignore` file with the one in this repo.

**Comment by lorikrell** [comment]
Hello @hostep , I'm adding content to the documentation for this information. If development makes changes to automatically do this, having it in the docs is just a good verification step.

**Comment by haljeshi** [comment]
I would prefer the upgrade process not to update the `.gitignore` file (i.e. to stay the way it's now). That's because I have already customized the ignore file according to my team preferences and to ignore custom folders that we have created for custom extensions.

But I agree with the suggestion to add the:

`/generated/*
!/generated/.htaccess`

to the `.gitignore` file.

**Comment by YPyltiai** [comment]
@hostep , it is fixed now. we re-worked the template, so it is much simpler now.

**Comment by seansan** [comment]
In the latest howto for 2.3.1. `/generated/*` is escaped as `# /generated/*` same goes for pub/static

https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-gitignore.html

So it seems it did/did not find its way in the official config guide?

I would imagine generated/* and pub/static/* ignored by default because the files are created. Correct?

**Comment by hostep** [comment]
@seansan: https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-gitignore.html has nothing to do with Magento Cloud as far as I know.

I agree you should ignore `generated/*` in `.gitignore`, that's also mentioned on the `Show .gitignore for development` section. The reason why they comment it out in `Show .gitignore for build and production`, is probably because they assume you put your build artifact in git and deploy it that way, but that's a bit strange if you ask me.

(I'm also not happy with the `.gitignore` in the cloud project btw, adding `*` in the file at the top was causing all kind of weird and unexpected things to happen when I last worked on a cloud project)
