### ISSUE TITLE
Install Community Edition on Magento Cloud server

### ISSUE THREAD

**Issue by osd-henry** [magento/magento-cloud#474]
Hello,

Has anyone tried to install CE on Magento Cloud server? We're developing a plugin which needs to be tested on both EE (works fine) and CE on the server. Many errors like missing class files (FrontController) or read-only file systems during cache cleaning happened during my deployment of CE on magento cloud. 

I've searched for all the possible solutions around the web but no hope. 

Could you help me with this please? Thank you.

**Comment by YPyltiai** [comment]
@osd-henry , you can use https://github.com/magento/magento-cloud-docker/ for testing purposes, it works with CE and will cover your use case. You will need to run it in production mode.

The issues you've seen are likely because not all the code was compiled during di:compile, causing issues later in the process.

**Comment by NadiyaS** [comment]
Hi @osd-henry,

I hope that you were able to run all necessary testing on cloud docker. But if you have any proposals or meet any issues, feel free to create appropriate issue in [magento-cloud-docker](https://github.com/magento/magento-cloud-docker)

I close this issue.
